name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {
            os: windows-2025,
            name: windows
          }
        - {
            os: macos-13,
            name: macos
          }
        - {
            os: ubuntu-24.04,
            name: ubuntu
          }
        version:
        - name: v5.0.7290-stable
          filename: v5.0.7290-stable
        - name: v5.0.7648-stable
          filename: v5.0.7648-stable
        - name: stable/5.1.8005
          filename: v5.1.8005-stable
        - name: stable/5.1.8104
          filename: v5.1.8104-stable
        - name: dev/5.2.8161
          filename: dev
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Update submodule
      run: |
        cd binaryninjaapi
        git fetch --tags
        git checkout --force ${{matrix.version.name}}
        git submodule update --init --recursive
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.config.name}}-${{matrix.version.filename}}
        path: ${{github.workspace}}/build/*NativePredicateSolver*
